/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.sql.*;
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_firstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CheckBox_male = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_phoneNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_signUp = new javax.swing.JButton();
        CheckBox_female = new javax.swing.JCheckBox();
        Password = new javax.swing.JPasswordField();
        btn_clearAll = new javax.swing.JButton();
        txt_userName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_close = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee's Sign Up Page");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        txt_firstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_firstNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_firstNameMousePressed(evt);
            }
        });
        txt_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstNameActionPerformed(evt);
            }
        });
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name:");

        txt_lastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lastNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_lastNameMousePressed(evt);
            }
        });
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name:");

        CheckBox_male.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CheckBox_male.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_male.setText("Male");
        CheckBox_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_maleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone Number:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Age:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address:");

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ageMousePressed(evt);
            }
        });
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });

        txt_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addressMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_addressMousePressed(evt);
            }
        });
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_addressKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Gender:");

        txt_phoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_phoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_phoneNumberMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_phoneNumberMousePressed(evt);
            }
        });
        txt_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNumberActionPerformed(evt);
            }
        });
        txt_phoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneNumberKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password:");

        btn_signUp.setBackground(new java.awt.Color(0, 255, 0));
        btn_signUp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_signUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_signUp.setText("Sign Up");
        btn_signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signUpActionPerformed(evt);
            }
        });

        CheckBox_female.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CheckBox_female.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox_female.setText("Female");
        CheckBox_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_femaleActionPerformed(evt);
            }
        });

        btn_clearAll.setBackground(new java.awt.Color(0, 255, 255));
        btn_clearAll.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_clearAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_clearAll.setText("Clear All");
        btn_clearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearAllActionPerformed(evt);
            }
        });

        txt_userName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userNameMousePressed(evt);
            }
        });
        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });
        txt_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userNameKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name:");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("View Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btn_close.setBackground(new java.awt.Color(255, 0, 0));
        btn_close.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 0, 0));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmpSIgnUpDisplay.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel9))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel7))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel14))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel12))
                                            .addComponent(jLabel10))
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(CheckBox_male, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(CheckBox_female))
                                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_clearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_signUp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel7)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel11)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel14)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel12)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox_male)
                                    .addComponent(CheckBox_female))
                                .addGap(25, 25, 25)
                                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txt_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(9, 9, 9)
                                .addComponent(jCheckBox1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_signUp)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btn_clearAll)
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_close)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String g = null ;


    private void txt_firstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameMouseClicked

    private void txt_firstNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameMousePressed

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void txt_lastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameMouseClicked

    private void txt_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameMousePressed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameKeyTyped

    private void txt_ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageMouseClicked

    private void txt_ageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ageMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageMousePressed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped

        char ch = evt.getKeyChar();
        
        
        if (!Character.isDigit(ch))
        {
        evt.consume();
        getToolkit().beep();
        }
       
        
    }//GEN-LAST:event_txt_ageKeyTyped

    private void txt_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressMouseClicked

    private void txt_addressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressMousePressed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressKeyTyped

    private void txt_phoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberMouseClicked

    private void txt_phoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneNumberMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberMousePressed

    private void txt_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberActionPerformed

    private void txt_phoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNumberKeyTyped

        char ch = evt.getKeyChar();
        
        
        if (!Character.isDigit(ch))
        {
        evt.consume();
        getToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_phoneNumberKeyTyped

    // Establish Connection
    public Connection getConnection(){
    
    String url,user,password;
    Connection con = null;
    url = "jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useSSL=false";
    user = "root";
    password = "abc1994";
   
    try{
        
        con = DriverManager.getConnection(url, user, password);
  
        
    }catch(Exception ex){
        ex.printStackTrace();
    }
    
    return con;
    }
    
    
    // Create Account
    public void createAccount(){
    
    String sql;
                             //                              int                  int
    sql = "insert into employees (user_name,first_name,last_name,age,gender,address,phone_number,password) value(?,?,?,?,?,?,?,?)";
    Connection con = null;
    PreparedStatement pst = null;
    boolean inserted = false ;
    
    try{
        
        con = getConnection();
        pst = con.prepareStatement(sql);
        
        pst.setString(1, txt_userName.getText());
        pst.setString(2, txt_firstName.getText());
        pst.setString(3, txt_lastName.getText());
        
        int AGE = Integer.parseInt(txt_age.getText());
        pst.setInt(4, AGE);
        
        // gender
        pst.setString(5, g); 
        
        
        pst.setString(6, txt_address.getText());
        
        pst.setString(7, txt_phoneNumber.getText());
        
        pst.setString(8, getPassword());
        
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Account Created");
        JOptionPane.showMessageDialog(rootPane, "Your User Name is : " + txt_userName.getText());
        con.close();
    }catch(Exception ex){
        ex.printStackTrace();
    }
    
    }
     
    
    
    public String getPassword (){
    String PASSWORD = Password.getText();
    return (PASSWORD);
    }
    
    // Check Input Fields
    public boolean flag (){
    
     boolean FLAG ;       
        
     if(txt_userName.getText().isEmpty())
     {
        JOptionPane.showMessageDialog(rootPane, "Please Enter User Name");
        FLAG = false;    
     }
     else if( txt_firstName.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Name");
         FLAG = false;
     }   
     else if(txt_lastName.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Last Name");
         FLAG = false;
     }     
     else if(txt_age.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Age");
         FLAG = false;
     }
     else if(   ! ( CheckBox_male.isSelected() || CheckBox_female.isSelected() )  )
     {
         JOptionPane.showMessageDialog(rootPane, "Please Select A Gender");
         FLAG = false;
     }
     else if(txt_address.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Address");
         FLAG = false;
     }
     else if(txt_phoneNumber.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Phone Number");
         FLAG = false;
     }
     else if(getPassword().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Password");
         FLAG = false;
     } 
     else if(g == null)
     {
         JOptionPane.showMessageDialog(rootPane, "Please Select a Gender");
         FLAG = false;
     }
     
     else {
     FLAG = true;
    
     }
      return (FLAG);
    }
    
    public boolean CheckUserName(){
        
    boolean check  = false;
    String sql = "select user_name from employees where user_name = ?";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs;
   
   if(txt_userName.getText().isEmpty())
   {
       JOptionPane.showMessageDialog(rootPane, "Please Enter User Name");
   }
   else{
       
    try{
    
        con = getConnection();
        
        pst = con.prepareStatement(sql);
        pst.setString(1,txt_userName.getText() );
        
        rs = pst.executeQuery();
        
        if(rs.next()){
        
        JOptionPane.showMessageDialog(rootPane, "This User Name Already Exist");    
        check = true;
       
        }else{
            check = false; 
        }
        
    }catch (Exception ex){
        ex.printStackTrace();
    }
    
   }
    return (check);
    }
    
    public void clear(){
    
     txt_userName.setText(null);
     txt_firstName.setText(null);
     txt_lastName.setText(null);
     txt_phoneNumber.setText(null);
     txt_address.setText(null);
     txt_age.setText(null);
     Password.setText(null);
        
     CheckBox_male.setSelected(false);
     CheckBox_female.setSelected(false);
     jCheckBox1.setSelected(false);    
    
    }
   
    
    private void btn_signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signUpActionPerformed
        
        int lengthUN ,lengthP;
        
        lengthUN = txt_userName.getText().toCharArray().length;
        lengthP = Password.getText().toCharArray().length;
        
        if ((flag() == true) &&(CheckUserName() == false))
        {
            if((lengthP < 4))
            {
                JOptionPane.showMessageDialog(rootPane, "Password length has to be more than 3 characters");
            }
            else if (lengthUN < 3)
            {
                JOptionPane.showMessageDialog(rootPane, "User Name length has to be more than 2 characters");
            }
            else
            {
            createAccount();
            clear();
            }
        }
        
    }//GEN-LAST:event_btn_signUpActionPerformed

    private void CheckBox_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_maleActionPerformed
       
        if(CheckBox_male.isSelected())
        {
            CheckBox_female.setSelected(false);
            g = "Male" ;
        }
       
    }//GEN-LAST:event_CheckBox_maleActionPerformed

    private void CheckBox_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_femaleActionPerformed
       
        if(CheckBox_female.isSelected())
        {
            CheckBox_male.setSelected(false);
            g = "Female";
        }
        
        
        
    }//GEN-LAST:event_CheckBox_femaleActionPerformed

    private void txt_userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameMouseClicked

    private void txt_userNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameMousePressed

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    private void txt_userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameKeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if(jCheckBox1.isSelected())
        {
            Password.setEchoChar((char)0);
        }
        else
        {
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_clearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearAllActionPerformed
        
       clear();
        
    }//GEN-LAST:event_btn_clearAllActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed

        System.exit(0);
        
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        Dashboard dshbrd = new Dashboard();
        dshbrd.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_female;
    private javax.swing.JCheckBox CheckBox_male;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clearAll;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_signUp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
