/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maaz
 */
public class ViewEmployees extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmployees
     */
    public ViewEmployees() {
        initComponents();
        ShowEmployeeInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        txt_phoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        CheckBox_male = new javax.swing.JCheckBox();
        CheckBox_female = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        btn_adminDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee Records");
        setMinimumSize(new java.awt.Dimension(1370, 619));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        table.setBackground(new java.awt.Color(255, 255, 153));
        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "First Name", "Last Name", "Age", "Gender", "Address", "Phone Number", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionBackground(new java.awt.Color(255, 102, 0));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User Name:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txt_userName.setEditable(false);
        txt_userName.setBackground(java.awt.Color.gray);
        txt_userName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_userName.setForeground(new java.awt.Color(255, 255, 255));
        txt_userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userNameMousePressed(evt);
            }
        });
        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });
        txt_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userNameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 41));

        txt_firstName.setBackground(java.awt.Color.gray);
        txt_firstName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_firstName.setForeground(new java.awt.Color(255, 255, 255));
        txt_firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_firstNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_firstNameMousePressed(evt);
            }
        });
        txt_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstNameActionPerformed(evt);
            }
        });
        txt_firstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstNameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_lastName.setBackground(java.awt.Color.gray);
        txt_lastName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_lastName.setForeground(new java.awt.Color(255, 255, 255));
        txt_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_lastNameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_lastNameMousePressed(evt);
            }
        });
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });
        txt_lastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastNameKeyTyped(evt);
            }
        });
        jPanel2.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Age:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txt_age.setBackground(java.awt.Color.gray);
        txt_age.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_age.setForeground(new java.awt.Color(255, 255, 255));
        txt_age.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_ageMousePressed(evt);
            }
        });
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ageKeyTyped(evt);
            }
        });
        jPanel2.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 160, 41));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        txt_address.setBackground(java.awt.Color.gray);
        txt_address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_address.setForeground(new java.awt.Color(255, 255, 255));
        txt_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_addressMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_addressMousePressed(evt);
            }
        });
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_addressKeyTyped(evt);
            }
        });
        jPanel2.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 160, 41));

        txt_phoneNumber.setBackground(java.awt.Color.gray);
        txt_phoneNumber.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        txt_phoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_phoneNumberMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_phoneNumberMousePressed(evt);
            }
        });
        txt_phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNumberActionPerformed(evt);
            }
        });
        txt_phoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_phoneNumberKeyTyped(evt);
            }
        });
        jPanel2.add(txt_phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 160, 41));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 453, -1, -1));

        Password.setBackground(java.awt.Color.gray);
        Password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 160, 41));

        CheckBox_male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckBox_male.setText("Male");
        CheckBox_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_maleActionPerformed(evt);
            }
        });
        jPanel2.add(CheckBox_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 59, -1));

        CheckBox_female.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CheckBox_female.setText("Female");
        CheckBox_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_femaleActionPerformed(evt);
            }
        });
        jPanel2.add(CheckBox_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("View Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 5));

        btn_update.setBackground(new java.awt.Color(0, 153, 0));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 102));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(0, 153, 153));
        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_close.setBackground(new java.awt.Color(255, 0, 0));
        btn_close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_adminDashboard.setBackground(new java.awt.Color(153, 153, 255));
        btn_adminDashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_adminDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_adminDashboard.setText("Back To Admin's Dashboard");
        btn_adminDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_update)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset))
                    .addComponent(btn_adminDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_close, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_reset))
                .addGap(40, 40, 40)
                .addComponent(btn_adminDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Do NOT DELETE
    private String g = null ;
    
    
    //Do NOT DELETE
    // Establishes Connection
    public Connection getConnection(){
    
    String url,user,password;
    Connection con = null;
    url = "jdbc:mysql://localhost:3306/inventory?autoReconnect=true&useSSL=false";
    user = "root";
    password = "abc1994";
   
    try{
        
        con = DriverManager.getConnection(url, user, password);
   //     JOptionPane.showMessageDialog(rootPane, "Database Connected");
        
    }catch(Exception ex){
        ex.printStackTrace();
    }
    
    return con;
    }
    
    
    //Do NOT DELETE
    // Populate jTable
    public ArrayList<Staff> empList(){
    
        ArrayList<Staff> list = new ArrayList ();
        
        String sql = "select * from employees";
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        Staff emp;
        try{
            
            con = getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            
            while (rs.next()){
            
            emp = new Staff(rs.getString(1), rs.getString(2),rs.getString(3),rs.getInt(4) ,rs.getString(5),rs.getString(6), rs.getInt(7),rs.getString(8) );
            list.add(emp);
            }
            con.close();
        }catch(Exception ex){
            
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
    return (list);
    }
    
    
    //Do NOT DELETE
    // 2 - Populate the JTable
    public void ShowEmployeeInTable()
    {
    //table
    ArrayList<Staff> list2 = empList();
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    
    Object[] row = new Object [9];
    
    model.setRowCount(0);
    
    for(int i = 0; i < list2.size(); i++)
    {
    row[0] = list2.get(i).getUserName();
    row[1] = list2.get(i).getFirstName();
    row[2] = list2.get(i).getLastName();
    row[3] = list2.get(i).getAge();
    row[4] = list2.get(i).getGender();
    
    row[5] = list2.get(i).getAddress();
    row[6] = list2.get(i).getPhoneNumber();
    row[7] = list2.get(i).getPassword();
    
    model.addRow(row);
    }
    
    }
    
    
    //Do NOT DELETE
    // Check Input Fields
    public boolean flag (){
    
     boolean FLAG ;       
        
     if(txt_userName.getText().isEmpty())
     {
        JOptionPane.showMessageDialog(rootPane, "Please Enter User Name");
        FLAG = false;    
     }
     else if( txt_firstName.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Name");
         FLAG = false;
     }   
     else if(txt_lastName.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Last Name");
         FLAG = false;
     }     
     else if(txt_age.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Age");
         FLAG = false;
     }     
     else if(txt_address.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Address");
         FLAG = false;
     }
     else if(txt_phoneNumber.getText().isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Phone Number");
         FLAG = false;
     }
     else if(String.valueOf(Password.getPassword()).isEmpty())
     {
         JOptionPane.showMessageDialog(rootPane, "Please Enter Password");
         FLAG = false;
     } 
     else if(g == null )
     {
         JOptionPane.showMessageDialog(rootPane, "Please Select a Gender");
         FLAG = false;
     }
     
     else {
     FLAG = true;
    
     }
      return (FLAG);
    }
    
    
    //Do NOT DELETE
    //  Update Account
    public void UpdateAccount(){
    
    String sql1,sql;
                             //                                 int                   int
    sql1 = "insert into employees (user_name,first_name,last_name,age,gender,address,phone_number,password) value(?,?,?,?,?,?,?,?)";
    sql = "update employees  set first_name = ?,last_name = ?, age = ?,gender = ?, address = ?, phone_number = ?, password = ?  where user_name = ?";
    Connection con = null;
    PreparedStatement pst = null;
    boolean inserted = false ;
    
    try{
        
        con = getConnection();
        pst = con.prepareStatement(sql);
        
        
        pst.setString(1, txt_firstName.getText());
        pst.setString(2, txt_lastName.getText());
        
        int AGE = Integer.parseInt(txt_age.getText());
        pst.setInt(3, AGE);
        
        // gender
        pst.setString(4, g); 
        
        
        pst.setString(5, txt_address.getText());
        
        pst.setString(6, txt_phoneNumber.getText());
        
        pst.setString(7, String.valueOf(Password.getPassword()));
        
         pst.setString(8, txt_userName.getText());
        
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Account Updated");
        
        con.close();
        
    }catch(Exception ex){
        ex.printStackTrace();
    }
    
    }
    
    
    //Do NOT DELETE
    // display values in textboxes
    public void show(int index){
    
    txt_userName.setText(table.getValueAt(index, 0).toString());
    
    txt_firstName.setText(table.getValueAt(index, 1).toString());
    
    txt_lastName.setText(table.getValueAt(index, 2).toString());
    
    txt_age.setText(table.getValueAt(index, 3).toString());
    
    if(table.getValueAt(index, 4).toString().equals("Male"))
        {
         CheckBox_female.setSelected(false);
         CheckBox_male.setSelected(true);
         g = "Male";
        }
    if(table.getValueAt(index, 4).toString().equals("Female"))
    {
        
        CheckBox_male.setSelected(false);
        CheckBox_female.setSelected(true);
        g = "Female";
        
    }
    
  
    txt_address.setText(table.getValueAt(index, 5).toString());
    
    txt_phoneNumber.setText(table.getValueAt(index, 6).toString());
    
    Password.setText(table.getValueAt(index, 7).toString());
    
    }
    
    
    //Do NOT DELETE
    public void resetValues(){
    
        table.clearSelection();
        
        txt_userName.setText(null);
        txt_firstName.setText(null);
        txt_lastName.setText(null);
        txt_age.setText(null);
        
        CheckBox_male.setSelected(false);
        CheckBox_female.setSelected(false);
        
        txt_address.setText(null);
        txt_phoneNumber.setText(null);
        Password.setText(null);
    }
  
    private void txt_userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameMouseClicked

    private void txt_userNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameMousePressed

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    private void txt_userNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameKeyTyped

    private void txt_firstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameMouseClicked

    private void txt_firstNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_firstNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameMousePressed

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_firstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameKeyTyped

    private void txt_lastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameMouseClicked

    private void txt_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_lastNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameMousePressed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_lastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastNameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameKeyTyped

    private void txt_ageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageMouseClicked

    private void txt_ageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ageMousePressed

        
    }//GEN-LAST:event_txt_ageMousePressed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyTyped

         char ch = evt.getKeyChar();
        
        
        if (!Character.isDigit(ch))
        {
        evt.consume();
        getToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_ageKeyTyped

    private void txt_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressMouseClicked

    private void txt_addressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_addressMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressMousePressed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressKeyTyped

    private void txt_phoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberMouseClicked

    private void txt_phoneNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phoneNumberMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberMousePressed

    private void txt_phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNumberActionPerformed

    private void txt_phoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phoneNumberKeyTyped

        char ch = evt.getKeyChar();
        
        if (!Character.isDigit(ch))
        {
        evt.consume();
        getToolkit().beep();
        }
        
    }//GEN-LAST:event_txt_phoneNumberKeyTyped

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        
        int lengthP;
        
        
        lengthP = Password.getText().toCharArray().length;
        
        if (flag() == true)
        {
            if((lengthP < 4))
            {
                JOptionPane.showMessageDialog(rootPane, "Password length has to be more than 3 characters");
            }
            else
            {
            UpdateAccount();
            ShowEmployeeInTable();
            }
        }
               
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        String sql = "delete from employees where user_name = ? ";
        Connection con = null;
        PreparedStatement pst = null;
        
        if (txt_userName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Please Select a Row");
        
        }else {
        
           try {
            con = getConnection();
            pst = con.prepareStatement(sql);
            
            pst.setString(1, txt_userName.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Staff Member Deleted");
            ShowEmployeeInTable();
            resetValues();
            con.close();
             
        }catch(Exception ex){
            
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        
        }
            
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed

        resetValues();
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void CheckBox_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_maleActionPerformed

        CheckBox_male.setSelected(true);
        if(CheckBox_male.isSelected())
        {
            CheckBox_female.setSelected(false);
            g = "Male" ;
        }
        
    }//GEN-LAST:event_CheckBox_maleActionPerformed

    private void CheckBox_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_femaleActionPerformed

        CheckBox_female.setSelected(true);
        if(CheckBox_female.isSelected())
        {
            CheckBox_male.setSelected(false);
            g = "Female";
        }

    }//GEN-LAST:event_CheckBox_femaleActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        int index = table.getSelectedRow();
        show(index);
        
    }//GEN-LAST:event_tableMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

        evt.consume();
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if(jCheckBox1.isSelected())
        {
            Password.setEchoChar((char)0);
        }
        else
        {
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_adminDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminDashboardActionPerformed
        
        DashboardAdmin da = new DashboardAdmin ();
        da.setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_btn_adminDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox_female;
    private javax.swing.JCheckBox CheckBox_male;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btn_adminDashboard;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_phoneNumber;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
